server:
 port: 8082
spring:
 datasource:
  url: jdbc:mysql://10.101.151.177:3306/vnpt_service?createDatabaseIfNotExist=true
  username: duong
  password: Vnpt@123
  driver-class-name: com.mysql.jdbc.Driver
 jpa:
  hibernate:
   naming:
    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  ddl-auto: update
  
eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://10.101.30.6:8716/eureka/
  instance: 
   ostname: auth_service