spring:
 datasource:
  url: jdbc:mysql://10.101.151.177:3306/vnpt_service?createDatabaseIfNotExist=true
  username: duong
  password: Vnpt@123
  driver-class-name: com.mysql.jdbc.Driver
 jpa:
  hibernate:
   naming:
    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingSteategyStandardImpl